### ISSUE TITLE
Solicitação para me tornar colaboradora

### ISSUE THREAD

**Issue by carolinafmacedo** [ramidedantas/GCMS-2024-2#3]
@ramidedantas solicitação de convite para me tornar colaboradora do repositório GCMS-2024-2

**Comment by ramidedantas** [comment]
@carolinafmacedo convite enviado.

**Comment by carolinafmacedo** [comment]
@ramidedantas solicito reenvio do convite

**Comment by ramidedantas** [comment]
@carolinafmacedo convite reenviado.
