### ISSUE TITLE
Solicitação para participar do repositório

### ISSUE THREAD

**Issue by KameGaKiru** [ramidedantas/GCMS-2024-2#4]
@ramidedantas, solicito o convite para me tornar colaborador do repositório GCMS-2024-2

**Comment by ramidedantas** [comment]
@KameGaKiru convite enviado.

**Comment by KameGaKiru** [comment]
Nome e @ incluídos no Readme.md

**Comment by ramidedantas** [comment]
ok @KameGaKiru, fechando issue.
