### ISSUE TITLE
Solicitação para me tornar colaborador

### ISSUE THREAD

**Issue by Neto-Pereira25** [ramidedantas/GCMS-2024-2#6]
Professor @ramidedantas, solicito convite para me tornar colaborador do repositório.

**Comment by ramidedantas** [comment]
@Neto-Pereira25 convite enviado.

**Comment by Neto-Pereira25** [comment]
Nome incluído na lista de colaboradores

**Comment by ramidedantas** [comment]
@Neto-Pereira25 ok, fechando issue.
