### ISSUE TITLE
Solicitação pra contribuir no repositório

### ISSUE THREAD

**Issue by RafaLG18** [ramidedantas/GCMS-2024-2#7]
Venho por meio dessa issue, solicitar para me tornar contribuidor desse repositório.

@ramidedantas

**Comment by ramidedantas** [comment]
@RafaLG18 convite enviado.

**Comment by RafaLG18** [comment]
Nome completo, e usuário, inserido no README.

**Comment by ramidedantas** [comment]
ok @RafaLG18, fechando issue.
